### ISSUE TITLE
run the classifier on dataset without od

### ISSUE THREAD

**Issue by mariasid** [H00N24/PV056-AutoML-testing-framework#18]
I want to run the classifier without od and od removed. How it can be done?

**Comment by H00N24** [comment]
Hi, it has been some time since I was working on this, so could you be a little bit more specific?
Every step after splitting datasets is using two directories input and output one. Where the output of one stage is the input for the next one. So you if you want to skip any step, simply change the input directories.

**Comment by mariasid** [comment]
running the main_clf.py would takes output from od removed . can it be be run without  going through the od and od removed. like in pipeline 1 readme
Pipeline 1: split data -> run classifiers -> (optional) statistics

**Comment by mariasid** [comment]
Is it  be like run split>od>remove[0%]>classifers?

**Comment by H00N24** [comment]
> Is it be like run split>od>remove[0%]>classifers?

Yes, you could, but it should not have a different result than the first pipeline. We are using WEKA filters to ignore outlier detection values + id fields (code below). 

https://github.com/H00N24/PV056-AutoML-testing-framework/blob/38b33e0cac9517f625ad1c83c0c6170230d3cd54/pv056_2019/classifiers.py#L106-L111


Could I ask what do you want to use it for? Maybe I could suggest some solutions.

**Comment by mariasid** [comment]
I was comparing the result of this framework with other od+rm methods. thanks for your help.
